/** Excel "Yeni Ürün takip" — column A row labels (0-based row index). */
export const URUN_TAKIP_EXCEL_ROWS = [
  { row: 0, key: "urunAdi", label: "Ürün Adı" },
  { row: 1, key: "baslangic", label: "İşlem Başlangıç Tarihi" },
  { row: 2, key: "tedarikci", label: "Tedarikçi" },
  { row: 3, key: "siparisAdedi", label: "Sipariş Adedi" },
  { row: 4, key: "sinif", label: "Hangi Sınıf" },
  { row: 5, key: "hammaddeMi", label: "Karışım Ürün mü /Hammadde mi?" },
  { row: 6, key: "siparisVerildi", label: "Ürün Siparişi Verildi mi?" },
  { row: 7, key: "fiyatAlindi", label: "Fiyat Alındı mı?" },
  { row: 8, key: "analizGerekiyor", label: "Analiz Gerekiyor mu?" },
  { row: 9, key: "hangiAnaliz", label: "Hangi Analiz Gerekiyor" },
  { row: 10, key: "analizBaslangic", label: "Analiz Başlangıç Tarihi" },
  { row: 11, key: "analizBitis", label: "Analiz Bitiş Tarihi" },
  { row: 12, key: "analizUcreti", label: "Analiz Ücreti Ne Kadar" },
  { row: 13, key: "spektHazirlandi", label: "Spekt Hazırlandı mı?" },
  { row: 14, key: "spektTeslimTarihi", label: "Spekt Teslim Tarihi" },
  { row: 15, key: "spektKimTeslim", label: "Spekt'i Kim Teslim Ediyor?" },
  { row: 16, key: "spektUcreti", label: "Spekt Ücreti Ne Kadar" },
  { row: 17, key: "ambalajGerekiyor", label: "Ambalaj & Etiket Gerekiyor mu" },
  { row: 18, key: "ambalajTasarimYapildi", label: "Ambalaj Tasarımı Yapıldı mı ?" },
  { row: 19, key: "ambalajTasarimTeslim", label: "Ambalaj & Etiket Tasarımı Teslim Tarihi" },
  { row: 20, key: "ambalajTasarimKim", label: "Kim Teslim Ediyor." },
  { row: 21, key: "ambalajTasarimUcreti", label: "Ambalaj Tasarım Ücreti Ne Kadar ?" },
  { row: 22, key: "ambalajTasarimOdendi", label: "Ambalaj Tasarım Ödemesi Yapıldı mı ?" },
  { row: 23, key: "ambalajBasimYapildi", label: "Ambalaj Basımı Yapıldı mı ?" },
  { row: 24, key: "ambalajBasimTeslim", label: "Ambalaj Basım Teslim Tarihi" },
  { row: 25, key: "ambalajBasimKim", label: "Kim Teslim Ediyor?" },
  { row: 26, key: "ambalajBasimUcreti", label: "Ambalaj Basım Ücreti Ne Kadar ?" },
  { row: 27, key: "ambalajBasimOdendi", label: "Ambalaj Basım Ücreti Ödendi mi ?" },
  { row: 28, key: "uretimeGecildi", label: "Üretime Geçildi mi ?" },
  { row: 29, key: "ureticiKim", label: "Üretici Kim ?" },
  { row: 30, key: "uretimTamamlanmaTahmini", label: "Üretim Tamamlanma Tarihi Tahmini" },
  { row: 31, key: "uretimMaliyeti", label: "Üretim Maliyeti Ne Kadar" },
  { row: 32, key: "uretimUcretiOdendi", label: "Üretim Ücreti Ödendi mi ?" },
  { row: 33, key: "dolumGerekiyor", label: "Dolum Gerekiyor mu ?" },
  { row: 34, key: "dolumYapildi", label: "Dolum Yapıldı mı ?" },
  { row: 35, key: "dolumVade", label: "Dolum Vadedilen Tarih" },
  { row: 36, key: "dolumKim", label: "Dolumu Kim Yapıyor" },
  { row: 37, key: "dolumUcreti", label: "Dolum Ücreti Ne Kadar ?" },
  { row: 38, key: "dolumUcretiOdendi", label: "Dolum Ücreti Ödendi mi ?" },
  { row: 39, key: "sevkiyatYapildi", label: "Sevkiyat Yapıldı mı" },
  { row: 40, key: "nakliyeUcretiVar", label: "Nakliye Ücreti Var mı ?" },
  { row: 41, key: "nakliyeUcreti", label: "Nakliye Ücreti Ne Kadar" },
  { row: 42, key: "nakliyeOdendi", label: "Nakliye Ücreti Ödendi mi ?" },
  { row: 43, key: "depoyaGiris", label: "Depoya Giriş Yapıldı mı ?" },
  { row: 44, key: "depoyaGirisTarihi", label: "Depoya Giriş Tarihi" },
  { row: 45, key: "fotograflamaYapildi", label: "Fotoğraflama Yapıldı mı ?" },
  { row: 46, key: "fotograflamaUcreti", label: "Fotoğraflama Ücreti" },
  { row: 47, key: "fotografOdeme", label: "Ödeme Yapıldı mı ?" },
  { row: 48, key: "webYuklendi", label: "Web Sitesine Yüklendi mi?" },
  { row: 49, key: "webYuklemeTarihi", label: "Tahmini Yüklenme /Yüklenme Tarihi" },
] as const;

/** Product columns start at Excel column M (0-based index 12). */
export const URUN_TAKIP_FIRST_COL = 12;

export const URUN_TAKIP_TABLE_COLUMNS = URUN_TAKIP_EXCEL_ROWS.map(({ key, label }) => ({
  key,
  label,
}));
